### ISSUE TITLE
Implement a barebones Electron app

### ISSUE THREAD

**Issue by jasozh** [CornellDataScience/sketchy#16]
Branch: `electron-app`

### Task at Hand
- Create a barebones Electron app that can run and display functions from our ML models.
- See Electron Forge to figure out how to build the Electron app into something that can be installed on macOS and Windows.

### Acceptance Criteria
- [ ] Key deliverable: there should be an installable `.exe` or `.dmg` file that I can install on Windows/macOS to access the Sketchy app. When the app opens, I should be able to click a button that invokes some random python function (could be print hello world).

### Notes
- See `python-shell` in https://stackoverflow.com/questions/55668283/run-a-tensorflow-saved-model-in-electron-app
- See the Electron documentation here: https://www.electronjs.org/docs/latest/tutorial/quick-start
- See Electron Forge documentation here: https://www.electronforge.io/

**Comment by ATU2119** [comment]
Finished ticket, sorry took so long, had to figure out how to use IPC listener.
